# グローバル設定
expiration_days: 3  # 履歴を削除する日数
max_entries: 10  # 投稿する記事の上限

# 各ジャンルの設定
genres:
  英字記事:
    rss_feeds:
      # CNN.com - RSS Channel - World
      - "http://rss.cnn.com/rss/cnn_world.rss"
      # BBC News - World
      - "https://feeds.bbci.co.uk/news/world/rss.xml"     
  ゲーム・ガジェット:
    rss_feeds:
      # 4Gamer.net − 注目の記事のみ
      - "https://www.4gamer.net/rss/news_topics.xml"
      # Game*Spark
      - "https://www.gamespark.jp/rss20/index.rdf"
      # GAZLOG
      - "https://gazlog.jp/feed/"
      # automaton-media
      - "https://automaton-media.com/feed/"
      # cgworld.jp
      - "https://cgworld.jp/atom.xml"      
  暮らし:
    rss_feeds:
      # NHKニュース|主要トピック
      - "https://www.nhk.or.jp/rss/news/cat0.xml"
      # NHKニュース|社会
      - "https://www.nhk.or.jp/rss/news/cat1.xml"
      # NHKニュース|文化・エンタメ
      - "https://www.nhk.or.jp/rss/news/cat2.xml"
      # NHKニュース|政治
      - "https://www.nhk.or.jp/rss/news/cat4.xml"
      # NHKニュース|経済
      - "https://www.nhk.or.jp/rss/news/cat5.xml"
      # NHKニュース|国際
      - "https://www.nhk.or.jp/rss/news/cat6.xml"
テスト記事:
    rss_feeds:
      # ファミ通テスト
      - "https://politepol.com/fd/ByXntyJpls0b.xml"
