# グローバル設定
expiration_days: 3  # 履歴を削除する日数
max_entries: 10  # 投稿する記事の上限

# 各ジャンルの設定
genres:
  4Gamer.net:
    rss_feeds:
      # 4Gamer.net − 注目の記事のみ
      - "https://www.4gamer.net/rss/news_topics.xml"
  Game*Spark:
    rss_feeds:
      # Game*Spark
      - "https://www.gamespark.jp/rss20/index.rdf"
  AUTOMATON:
    rss_feeds:
      # automaton-media
      - "https://automaton-media.com/feed/"
  CGWORLD.jP:
    rss_feeds:
      # cgworld.jp
      - "https://cgworld.jp/atom.xml"      
  新着アセット情報:
    rss_feeds:
      # AssetStoreまとめ割引情報beta
      - "https://assetsale.herokuapp.com/ja/publisher_sales_feed.rss"
  ファミ通.com_新着:
    rss_feeds:
      # ファミ通.com_新着
      - "https://politepol.com/fd/TGhWLIBmzwbU.xml"
  ゲームメーカーズ:
    rss_feeds:
      # ゲームメーカーズ_新着
      - "https://gamemakers.jp/category/news/feed/"
